# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import gallery_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_auto_20170812_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(editable=False, upload_to=gallery_app.models.image_upload_path),
        ),
    ]
