# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 05:50
from __future__ import unicode_literals

from django.db import migrations
import gallery_app.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_auto_20170813_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=gallery_app.models.image_upload_path),
        ),
    ]
